name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  test-walle-build:
    name: Test with go 1.16 on ubuntu-latest
    runs-on: ubuntu-latest
    environment:
      name: test-walle

    steps:
      # 1.设置打包 tag。
      - name: Export tag
        run: |
          echo "NOW::$(date +'%Y_%m_%d_%H_%M')" >> $GITHUB_ENV

      # 2.下载源码。
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # 3.构建镜像，并将镜像 push 到远程仓库
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-GitHub-Action@master
        with:
          name: registry.cn-hangzhou.aliyuncs.com/tanwuyang/walle-test:$NOW  # docker image 的名字
          username: ${{ secrets.DOCKER_USERNAME}} # 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 密码
          registry: registry.cn-hangzhou.aliyuncs.com # 腾讯云Registry
          dockerfile: Dockerfile # 指定 Dockerfile 的位置
          tag_names: false # 是否将 release 的 tag 作为 docker image 的 tag
