name: Build Docker Image

on:
  push:
    branches:
      - master

jobs:
  test-walle-build:

    runs-on: ubuntu-latest

    steps:
      # 1.设置打包 tag。
      - name: Get current date
        id: date
        run: echo "::set-output name=today::$(date +'%Y-%m-%d')"

      # 2.下载源码。
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      # 3.构建镜像，并将镜像 push 到远程仓库
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-GitHub-Action@master
        with:
          name: registry.cn-hangzhou.aliyuncs.com/tanwuyang/walle-test   # docker image 的名字
          username: ${{ secrets.DOCKER_USERNAME}} # 用户名
          password: ${{ secrets.DOCKER_PASSWORD }} # 密码
          registry: registry.cn-hangzhou.aliyuncs.com # 腾讯云Registry
          dockerfile: Dockerfile # 指定 Dockerfile 的位置
          tags: "latest,${{ steps.date.outputs.today }}"

